const esbuild = require('esbuild');
const path = require('path');

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository:
https://github.com/yourusername/obsidian-ai-text-processing
*/
`;

const prod = process.argv[2] === 'production';

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ['main.js'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  watch: !prod,
  target: 'es2016',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
}).catch(() => process.exit(1));